-- Vereen Electro Froid production seed
-- Use on a clean database or after truncating target tables.

INSERT INTO brand_partners (name, logo_url, website_url, sort_order) VALUES
('Whirlpool', NULL, 'https://www.whirlpool.com/', 1),
('Samsung', NULL, 'https://www.samsung.com/', 2),
('Ariston', NULL, 'https://www.ariston.com/', 3),
('Bosch', NULL, 'https://www.bosch-home.com/', 4),
('AUX', NULL, 'https://www.auxair.com/', 5),
('LG', NULL, 'https://www.lg.com/', 6),
('Daikin', NULL, 'https://www.daikin.com/', 7),
('Carrier', NULL, 'https://www.carrier.com/', 8);

INSERT INTO products (
  slug, category, brand,
  name_fr, name_ar, name_en,
  description_fr, description_ar, description_en,
  price_mad, price_display_fr, price_display_ar, price_display_en,
  image_url, gallery_urls,
  is_featured, is_active, sort_order
) VALUES
(
  'whirlpool-french-door-refrigerator',
  'refrigeration',
  'Whirlpool',
  'Refrigerateur French Door Whirlpool',
  'ثلاجة فرنش دور ويرلبول',
  'Whirlpool French Door Refrigerator',
  'Grande capacite, rangement flexible, ideal pour les familles et les commerces.',
  'سعة كبيرة وتخزين مرن للعائلات والمحلات.',
  'Large capacity, flexible storage, ideal for families and shops.',
  15900, 'A partir de 15 900 MAD', 'ابتداء من 15,900 درهم', 'From 15,900 MAD',
  'https://picsum.photos/seed/whirlpool-fridge/1200/900',
  ARRAY['https://picsum.photos/seed/whirlpool-fridge-1/1200/900', 'https://picsum.photos/seed/whirlpool-fridge-2/1200/900'],
  true, true, 1
),
(
  'whirlpool-front-load-washer',
  'washing_machine',
  'Whirlpool',
  'Machine a laver Front Load Whirlpool',
  'غسالة أمامية ويرلبول',
  'Whirlpool Front Load Washer',
  'Efficacite de lavage, programmes delicates, faible consommation d eau.',
  'كفاءة غسيل وبرامج لطيفة واستهلاك منخفض للماء.',
  'Efficient wash performance, delicate cycles and lower water use.',
  7490, 'A partir de 7 490 MAD', 'ابتداء من 7,490 درهم', 'From 7,490 MAD',
  'https://picsum.photos/seed/whirlpool-washer/1200/900',
  ARRAY['https://picsum.photos/seed/whirlpool-washer-1/1200/900'],
  true, true, 2
),
(
  'samsung-windfree-split-ac',
  'climatisation',
  'Samsung',
  'Climatiseur Samsung WindFree',
  'مكيف سامسونج ويند فري',
  'Samsung WindFree Split AC',
  'Confort silencieux avec diffusion douce de l air et pilotage intelligent.',
  'راحة هادئة مع توزيع لطيف للهواء وتحكم ذكي.',
  'Quiet comfort with gentle airflow diffusion and smart control.',
  6290, 'A partir de 6 290 MAD', 'ابتداء من 6,290 درهم', 'From 6,290 MAD',
  'https://picsum.photos/seed/samsung-ac/1200/900',
  ARRAY['https://picsum.photos/seed/samsung-ac-1/1200/900', 'https://picsum.photos/seed/samsung-ac-2/1200/900'],
  true, true, 3
),
(
  'samsung-bespoke-ac',
  'climatisation',
  'Samsung',
  'Climatiseur Samsung Bespoke AI',
  'مكيف سامسونج بيسبوك AI',
  'Samsung Bespoke AI AC',
  'Design premium, gestion intelligente de la temperature et de la consommation.',
  'تصميم فاخر مع إدارة ذكية للحرارة واستهلاك الطاقة.',
  'Premium design with intelligent temperature and energy management.',
  8990, 'A partir de 8 990 MAD', 'ابتداء من 8,990 درهم', 'From 8,990 MAD',
  'https://picsum.photos/seed/samsung-bespoke/1200/900',
  ARRAY['https://picsum.photos/seed/samsung-bespoke-1/1200/900'],
  true, true, 4
),
(
  'ariston-kairos-thermo-solar',
  'solar',
  'Ariston',
  'Chauffe-eau solaire Ariston Kairos',
  'سخان شمسي أريستون كايروس',
  'Ariston Kairos Solar Water Heater',
  'Solaire thermique pour eau chaude sanitaire, pense pour les foyers marocains.',
  'نظام شمسي حراري للماء الساخن المنزلي مناسب للمنازل المغربية.',
  'Thermal solar hot water solution designed for Moroccan homes.',
  8990, 'A partir de 8 990 MAD', 'ابتداء من 8,990 درهم', 'From 8,990 MAD',
  'https://picsum.photos/seed/ariston-solar/1200/900',
  ARRAY['https://picsum.photos/seed/ariston-solar-1/1200/900'],
  true, true, 5
),
(
  'bosch-serie-6-dishwasher',
  'dishwasher',
  'Bosch',
  'Lave-vaisselle Bosch Serie 6',
  'غسالة صحون بوش سيريز 6',
  'Bosch Serie 6 Dishwasher',
  'Silencieux, fiable et adapte aux cuisines modernes a forte demande.',
  'هادئة وموثوقة ومناسبة للمطابخ العصرية ذات الاستخدام المكثف.',
  'Quiet, reliable and built for modern kitchens with high daily demand.',
  7990, 'A partir de 7 990 MAD', 'ابتداء من 7,990 درهم', 'From 7,990 MAD',
  'https://picsum.photos/seed/bosch-dishwasher/1200/900',
  ARRAY['https://picsum.photos/seed/bosch-dishwasher-1/1200/900'],
  true, true, 6
),
(
  'bosch-series-8-washer',
  'washing_machine',
  'Bosch',
  'Machine a laver Bosch Serie 8',
  'غسالة بوش سيريز 8',
  'Bosch Serie 8 Washing Machine',
  'Lavage precis, moteurs inverter et cycle rapide pour usage intensif.',
  'غسيل دقيق ومحركات إنفرتر ودورة سريعة للاستخدام المكثف.',
  'Precision washing, inverter motors and quick cycles for intensive use.',
  8490, 'A partir de 8 490 MAD', 'ابتداء من 8,490 درهم', 'From 8,490 MAD',
  'https://picsum.photos/seed/bosch-washer/1200/900',
  ARRAY['https://picsum.photos/seed/bosch-washer-1/1200/900'],
  false, true, 7
),
(
  'aux-q-series-split-ac',
  'climatisation',
  'AUX',
  'Climatiseur AUX Q-Series',
  'مكيف AUX Q-Series',
  'AUX Q-Series Split AC',
  'Serie inverter pour logement et commerce avec demarrage rapide et economie d energie.',
  'سلسلة إنفرتر للمنازل والمحلات مع تشغيل سريع وتوفير للطاقة.',
  'Inverter series for homes and shops with fast start-up and energy savings.',
  4990, 'A partir de 4 990 MAD', 'ابتداء من 4,990 درهم', 'From 4,990 MAD',
  'https://picsum.photos/seed/aux-ac/1200/900',
  ARRAY['https://picsum.photos/seed/aux-ac-1/1200/900', 'https://picsum.photos/seed/aux-ac-2/1200/900'],
  true, true, 8
),
(
  'aux-multi-split-inverter',
  'climatisation',
  'AUX',
  'Système Multi-Split AUX',
  'نظام AUX متعدد الوحدات',
  'AUX Multi-Split Inverter',
  'Solution flexible pour plusieurs pieces avec une seule unite exterieure.',
  'حل مرن لعدة غرف مع وحدة خارجية واحدة.',
  'Flexible solution for multiple rooms with a single outdoor unit.',
  12990, 'A partir de 12 990 MAD', 'ابتداء من 12,990 درهم', 'From 12,990 MAD',
  'https://picsum.photos/seed/aux-multisplit/1200/900',
  ARRAY['https://picsum.photos/seed/aux-multisplit-1/1200/900'],
  false, true, 9
),
(
  'lg-dual-inverter-ac',
  'climatisation',
  'LG',
  'Climatiseur LG Dual Inverter',
  'مكيف LG Dual Inverter',
  'LG Dual Inverter AC',
  'Compressor inverter pour une temperature stable et un niveau sonore reduit.',
  'ضاغط إنفرتر لحرارة مستقرة ومستوى ضجيج منخفض.',
  'Inverter compressor for stable temperature and reduced noise.',
  5790, 'A partir de 5 790 MAD', 'ابتداء من 5,790 درهم', 'From 5,790 MAD',
  'https://picsum.photos/seed/lg-ac/1200/900',
  ARRAY['https://picsum.photos/seed/lg-ac-1/1200/900'],
  false, true, 10
),
(
  'lg-instaview-refrigerator',
  'refrigeration',
  'LG',
  'Refrigerateur LG InstaView',
  'ثلاجة LG InstaView',
  'LG InstaView Refrigerator',
  'Refrigeration haut de gamme avec design moderne et gestion intelligente.',
  'ثلاجة راقية بتصميم عصري وإدارة ذكية.',
  'Premium refrigeration with a modern design and smart management.',
  13490, 'A partir de 13 490 MAD', 'ابتداء من 13,490 درهم', 'From 13,490 MAD',
  'https://picsum.photos/seed/lg-fridge/1200/900',
  ARRAY['https://picsum.photos/seed/lg-fridge-1/1200/900'],
  false, true, 11
),
(
  'daikin-perfera-wall-mounted',
  'climatisation',
  'Daikin',
  'Climatiseur mural Daikin Perfera',
  'مكيف دايكن بيرفيرا جداري',
  'Daikin Perfera Wall Mounted AC',
  'Serie murale reconnue pour le confort, le silence et la regulation precise.',
  'سلسلة جدارية معروفة بالراحة والهدوء والتنظيم الدقيق.',
  'Wall-mounted series known for comfort, quiet operation and precise regulation.',
  7490, 'A partir de 7 490 MAD', 'ابتداء من 7,490 درهم', 'From 7,490 MAD',
  'https://picsum.photos/seed/daikin-ac/1200/900',
  ARRAY['https://picsum.photos/seed/daikin-ac-1/1200/900', 'https://picsum.photos/seed/daikin-ac-2/1200/900'],
  false, true, 12
),
(
  'carrier-infinity-system',
  'climatisation',
  'Carrier',
  'Carrier Infinity System',
  'نظام كاريير إنفينيتي',
  'Carrier Infinity System',
  'Solution HVAC haut rendement pour villas, bureaux et commerces.',
  'حل HVAC عالي الكفاءة للفلل والمكاتب والمحلات.',
  'High-efficiency HVAC solution for villas, offices, and shops.',
  14990, 'A partir de 14 990 MAD', 'ابتداء من 14,990 درهم', 'From 14,990 MAD',
  'https://picsum.photos/seed/carrier-hvac/1200/900',
  ARRAY['https://picsum.photos/seed/carrier-hvac-1/1200/900'],
  false, true, 13
);

INSERT INTO spare_parts (
  slug, part_number, compatible_brands, compatible_categories,
  name_fr, name_ar, name_en,
  description_fr, description_ar, description_en,
  price_mad, image_url, in_stock, is_active, sort_order
) VALUES
(
  'inverter-compressor-ac',
  'COMP-AC-INV-01',
  ARRAY['whirlpool','samsung','aux','lg','daikin','carrier'],
  ARRAY['climatisation'::product_category],
  'Compresseur inverter AC',
  'ضاغط إنفرتر للتكييف',
  'Inverter AC Compressor',
  'Compresseur de remplacement pour climatiseurs split et multi-split.',
  'ضاغط بديل لمكيفات السبليت والمولتي سبليت.',
  'Replacement compressor for split and multi-split AC systems.',
  1890,
  'https://picsum.photos/seed/part-compressor/900/700',
  true, true, 1
),
(
  'r410a-refrigerant',
  'GAS-R410A',
  ARRAY['aux','carrier','daikin','lg','samsung'],
  ARRAY['climatisation'::product_category],
  'Gaz refrigerant R410A',
  'غاز تبريد R410A',
  'R410A Refrigerant Gas',
  'Recharge pour installations de climatisation compatibles R410A.',
  'إعادة شحن لأنظمة التكييف المتوافقة مع R410A.',
  'Recharge gas for R410A-compatible AC installations.',
  480,
  'https://picsum.photos/seed/part-gas/900/700',
  true, true, 2
),
(
  'washing-machine-motor',
  'MOT-WM-230',
  ARRAY['whirlpool','samsung','bosch','lg'],
  ARRAY['washing_machine'::product_category],
  'Moteur machine a laver',
  'محرك غسالة',
  'Washing Machine Motor',
  'Moteur pour machines a laver front load et top load.',
  'محرك لغسالات التحميل الأمامي والعلوي.',
  'Motor for front-load and top-load washing machines.',
  1190,
  'https://picsum.photos/seed/part-motor/900/700',
  true, true, 3
),
(
  'universal-thermostat',
  'THERM-UNI-01',
  ARRAY['ariston','bosch','lg','whirlpool'],
  ARRAY['refrigeration'::product_category,'water_heater'::product_category],
  'Thermostat universel',
  'ثرموستات شامل',
  'Universal Thermostat',
  'Thermostat de controle pour refrigeration et chauffage deau.',
  'ثرموستات للتحكم في التبريد وتسخين المياه.',
  'Control thermostat for refrigeration and water heating.',
  260,
  'https://picsum.photos/seed/part-thermostat/900/700',
  true, true, 4
),
(
  'ac-remote-control',
  'REMOTE-AC-01',
  ARRAY['aux','daikin','carrier','samsung'],
  ARRAY['climatisation'::product_category],
  'Telecommande AC',
  'ريموت تكييف',
  'AC Remote Control',
  'Telecommande universelle de remplacement pour plusieurs marques.',
  'ريموت بديل شامل لعدة علامات تجارية.',
  'Universal replacement remote for multiple brands.',
  190,
  'https://picsum.photos/seed/part-remote/900/700',
  true, true, 5
),
(
  'water-pump',
  'PUMP-WTR-10',
  ARRAY['ariston','bosch','whirlpool'],
  ARRAY['dishwasher'::product_category,'washing_machine'::product_category],
  'Pompe a eau',
  'مضخة مياه',
  'Water Pump',
  'Pompe de remplacement pour appareils menagers.',
  'مضخة بديلة للأجهزة المنزلية.',
  'Replacement pump for household appliances.',
  340,
  'https://picsum.photos/seed/part-pump/900/700',
  true, true, 6
),
(
  'ac-capacitor',
  'CAP-AC-05',
  ARRAY['aux','carrier','daikin','lg'],
  ARRAY['climatisation'::product_category],
  'Condensateur AC',
  'مكثف تكييف',
  'AC Capacitor',
  'Piece de demarrage pour compresseurs et ventilateurs.',
  'قطعة تشغيل للضواغط والمراوح.',
  'Start component for compressors and fans.',
  155,
  'https://picsum.photos/seed/part-capacitor/900/700',
  true, true, 7
),
(
  'dishwasher-heating-element',
  'HEAT-DW-01',
  ARRAY['bosch','whirlpool','lg'],
  ARRAY['dishwasher'::product_category],
  'Resistance lave-vaisselle',
  'عنصر تسخين غسالة الصحون',
  'Dishwasher Heating Element',
  'Element de chauffe pour lave-vaisselle domestiques.',
  'عنصر تسخين لغسالات الصحون المنزلية.',
  'Heating element for domestic dishwashers.',
  280,
  'https://picsum.photos/seed/part-heater/900/700',
  true, true, 8
),
(
  'fridge-door-gasket',
  'GSK-FR-01',
  ARRAY['whirlpool','bosch','lg'],
  ARRAY['refrigeration'::product_category,'freezer'::product_category],
  'Joint de porte refrigerateur',
  'جلدة باب الثلاجة',
  'Fridge Door Gasket',
  'Joint de remplacement pour refrigerateurs et congelateurs.',
  'جلدة بديلة للثلاجات والمجمدات.',
  'Replacement gasket for refrigerators and freezers.',
  220,
  'https://picsum.photos/seed/part-gasket/900/700',
  true, true, 9
),
(
  'solar-safety-valve',
  'SOL-VLV-02',
  ARRAY['ariston'],
  ARRAY['solar'::product_category,'water_heater'::product_category],
  'Soupape de securite solaire',
  'صمام أمان شمسي',
  'Solar Safety Valve',
  'Composant de securite pour systemes solaires thermiques.',
  'مكون أمان لأنظمة الطاقة الشمسية الحرارية.',
  'Safety component for thermal solar systems.',
  180,
  'https://picsum.photos/seed/part-valve/900/700',
  true, true, 10
);

INSERT INTO blog_posts (
  slug,
  title_fr, title_ar, title_en,
  excerpt_fr, excerpt_ar, excerpt_en,
  content_fr, content_ar, content_en,
  tags, is_published, published_at
) VALUES
(
  'choisir-climatiseur-maroc',
  'Comment choisir le bon climatiseur pour votre maison au Maroc',
  'كيف تختار المكيف المناسب لمنزلك في المغرب',
  'How to choose the right AC for your home in Morocco',
  'Guide pratique pour dimensionner un climatiseur selon votre espace et votre usage.',
  'دليل عملي لاختيار سعة المكيف حسب المساحة وطبيعة الاستعمال.',
  'Practical guide to sizing an AC for your space and usage.',
  '# Choisir un climatiseur au Maroc\n\nLe climat marocain demande une selection precise. Pour un salon expose au soleil, privilegiez un split inverter avec bonne efficacite energetique. Pour une villa ou un commerce, pensez a la puissance, a la hauteur sous plafond, a l isolation et au debit d air.\n\n## Points a verifier\n- Surface a refroidir\n- Exposition solaire\n- Type de vitrage\n- Isolation des murs et du toit\n- Usage journalier et nombre d occupants\n\nChez Vereen Electro Froid, nous recommandons une visite technique quand la configuration est complexe. Cela evite le surdimensionnement et les factures elevees.',
  '# كيف تختار المكيف في المغرب\n\nالمناخ المغربي يتطلب اختيارا دقيقا. بالنسبة لغرفة معيشة معرضة للشمس، يفضل مكيف إنفرتر بكفاءة طاقة عالية. أما الفلل والمحلات التجارية، فيجب الانتباه إلى القدرة والمساحة وعزل الجدران وسقف الغرفة.\n\n## ما الذي يجب فحصه\n- المساحة المطلوب تبريدها\n- التعرض للشمس\n- نوع الزجاج\n- عزل الجدران والسقف\n- عدد المستخدمين والوقت اليومي\n\nفي Vereen Electro Froid نوصي بمعاينة تقنية عندما تكون الوضعية معقدة لتجنب المبالغة في السعة وارتفاع الفاتورة.',
  '# Choosing an AC in Morocco\n\nMorocco''s climate requires careful sizing. For a sun-exposed living room, choose an inverter split with strong energy efficiency. For villas or shops, pay attention to capacity, ceiling height, insulation and airflow.\n\n## Checklist\n- Room area\n- Sun exposure\n- Window glazing\n- Wall and roof insulation\n- Daily usage and occupancy\n\nVereen Electro Froid recommends a technical visit when the layout is complex to avoid oversizing and high bills.',
  ARRAY['climatisation','guide','morocco'], true, NOW()
),
(
  'chauffe-eau-solaire-vs-electrique',
  'Chauffe-eau solaire vs electrique : quelle solution pour le Maroc',
  'السخان الشمسي أم الكهربائي: ما الحل المناسب للمغرب',
  'Solar vs electric water heater: which is better for Morocco',
  'Comparaison claire des couts, de la maintenance et du retour sur investissement.',
  'مقارنة واضحة للتكاليف والصيانة والعائد على الاستثمار.',
  'Clear comparison of cost, maintenance and return on investment.',
  '# Solaire ou electrique ?\n\nPour de nombreux foyers marocains, le chauffe-eau solaire est la solution la plus rationnelle sur le moyen terme. L investissement initial est plus eleve, mais la consommation baisse fortement et l entretien reste simple.\n\n## Quand choisir le solaire\n- Usage familial stable\n- Toit avec bonne exposition\n- Objectif de reduction de facture\n- Volonte de limiter la dependance au reseau\n\n## Quand garder l electrique\n- Residence temporaire\n- Faible consommation d eau chaude\n- Absence de toiture exploitable\n\nNous proposons des installations thermiques Ariston avec suivi et maintenance periodique.',
  '# شمسي أم كهربائي؟\n\nبالنسبة للعديد من الأسر المغربية، يعتبر السخان الشمسي الحل الأكثر منطقية على المدى المتوسط. صحيح أن الاستثمار الأولي أعلى، لكن الاستهلاك ينخفض بشكل كبير والصيانة تبقى بسيطة.\n\n## متى نختار الشمسي\n- استخدام عائلي مستمر\n- سطح ذو تعرض جيد للشمس\n- هدف تقليل الفاتورة\n- الرغبة في تقليل الاعتماد على الشبكة\n\n## متى يبقى الكهربائي مناسبا\n- إقامة مؤقتة\n- استهلاك منخفض للماء الساخن\n- عدم توفر سطح مناسب\n\nنوفر تركيبات حرارية من Ariston مع المتابعة والصيانة الدورية.',
  '# Solar vs electric water heater\n\nFor many Moroccan households, a solar water heater is the most rational medium-term choice. The upfront investment is higher, but running costs fall dramatically and maintenance stays straightforward.\n\n## When solar wins\n- Stable family use\n- Good roof exposure\n- Energy bill reduction goal\n- Desire to reduce grid dependence\n\n## When electric is enough\n- Temporary residence\n- Low hot-water use\n- No usable roof space\n\nWe supply Ariston thermal systems with periodic follow-up and maintenance.',
  ARRAY['solar','water-heater','cost-analysis'], true, NOW()
),
(
  'maintenance-climatiseur-cote-maroc',
  'Guide dentretien de climatiseur pour la cote marocaine',
  'دليل صيانة المكيف على السواحل المغربية',
  'AC maintenance guide for Morocco''s coastal climate',
  'Lair salin et lhumidite exigent une maintenance plus reguliere.',
  'الهواء المالح والرطوبة يتطلبان صيانة أكثر انتظاما.',
  'Salt air and humidity require more regular maintenance.',
  '# Entretien climatiseur sur la cote\n\nDans les villes côtières, la poussiere, le sel et l humidite accelerent l encrassement des filtres, des echangeurs et des composants electroniques. Un plan de maintenance saisonnier evite les pannes et garde le rendement eleve.\n\n## Bonnes pratiques\n- Nettoyer les filtres tous les mois en saison chaude\n- Verifier le drainage des condensats\n- Rincer les batteries exterieures lorsque le site le permet\n- Contrôler les connexions electriques\n- Planifier un entretien annuel avant l ete\n\nVereen Electro Froid assure la maintenance preventive et corrective avec pieces d origine.',
  '# صيانة المكيف على الساحل\n\nفي المدن الساحلية، يؤدي الغبار والملح والرطوبة إلى تسريع اتساخ الفلاتر والمبادلات والمكونات الإلكترونية. خطة صيانة موسمية تمنع الأعطال وتحافظ على الكفاءة.\n\n## ممارسات جيدة\n- تنظيف الفلاتر كل شهر في موسم الحرارة\n- فحص تصريف المياه المتكثفة\n- غسل الوحدة الخارجية عند الإمكان\n- مراقبة التوصيلات الكهربائية\n- جدولة صيانة قبل الصيف\n\nنقوم في Vereen Electro Froid بالصيانة الوقائية والتصحيحية مع قطع أصلية.',
  '# AC maintenance on the coast\n\nIn coastal cities, dust, salt and humidity speed up filter fouling, exchanger buildup and electronic wear. A seasonal maintenance plan prevents faults and preserves efficiency.\n\n## Best practices\n- Clean filters monthly in hot season\n- Check condensate drainage\n- Rinse outdoor coils when site conditions allow\n- Inspect electrical connections\n- Schedule annual maintenance before summer\n\nVereen Electro Froid handles preventive and corrective maintenance with original parts.',
  ARRAY['maintenance','coast','hvac'], true, NOW()
);

INSERT INTO site_settings (key, value) VALUES
(
  'company_contact',
  '{
    "phone_numbers": ["0663572130", "0637237869"],
    "fax": "0539982020",
    "email": "vereenelectrofroid@gmail.com",
    "address": "Al Hoceima, Morocco",
    "whatsapp": "212663572130",
    "instagram": "@ste.vereen_electrofroid",
    "website": "https://stevereenelectrofroid.com"
  }'::jsonb
),
(
  'service_areas',
  '{
    "primary_city": "Al Hoceima",
    "secondary_cities": ["Taza", "Nador", "Tetouan", "Tangier", "Chefchaouen", "Larache"],
    "coverage": "Morocco national projects on request"
  }'::jsonb
),
(
  'seo_defaults',
  '{
    "canonical_domain": "https://stevereenelectrofroid.com",
    "brand_terms": ["Whirlpool", "Samsung", "Ariston", "Bosch", "AUX", "LG", "Daikin", "Carrier"]
  }'::jsonb
);
